FROM golang:1.26-alpine AS build
WORKDIR /src
COPY go.mod ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /app .

FROM gcr.io/distroless/static-debian12:latest
EXPOSE 80
COPY --from=build /app /app
ENTRYPOINT ["/app"]
